// src/agents/srtFixAgent.js
// Dùng AI để đối chiếu SRT từ Whisper với voice gốc, sửa text sai chính tả/số.
// CHỈ sửa nội dung text — KHÔNG thay đổi timestamp hay số lượng block SRT.
import { callAI } from '../services/aiRouter.js';

const SRT_FIX_PROMPT_VI = `Bạn là chuyên gia sửa phụ đề tiếng Việt.

NHIỆM VỤ:
Đây là lời dẫn gốc (voice) và SRT do Whisper tạo ra từ audio TTS.
Whisper đôi khi nghe sai từ, đặc biệt các từ tiếng Anh, số, ký hiệu.
Hãy đối chiếu SRT với voice gốc và sửa lại cho đúng.

QUY TẮC TUYỆT ĐỐI:
1. GIỮ NGUYÊN HOÀN TOÀN tất cả timestamp (VD: 00:00:01,500 --> 00:00:03,200)
2. GIỮ NGUYÊN số lượng SRT block — KHÔNG thêm, KHÔNG xóa block
3. GIỮ NGUYÊN phân bổ từ vào từng block (nếu block có 2 từ thì giữ 2 từ)
4. CHỈ được sửa nội dung text bên dưới timestamp
5. Ưu tiên dùng ký tự/số gốc từ voice (VD: "AI" thay "ây ai", "$108,000" thay "một trăm lẻ tám nghìn đô")
6. Giữ đúng hoa/thường tự nhiên của tiếng Việt
7. Trả về SRT hoàn chỉnh (text thuần, KHÔNG json, KHÔNG markdown)

VOICE GỐC:
{{VOICE}}

SRT TỪ WHISPER (cần kiểm tra và sửa nếu cần):
{{SRT}}`;

const SRT_FIX_PROMPT_EN = `You are an expert English subtitle corrector.

TASK:
Here is the original voice script and the SRT generated by Whisper from TTS audio.
Whisper sometimes mishears words, especially numbers, symbols, abbreviations, and brand names.
Compare the SRT with the original voice and fix any errors.

ABSOLUTE RULES:
1. KEEP ALL timestamps EXACTLY as-is (e.g. 00:00:01,500 --> 00:00:03,200)
2. KEEP the same number of SRT blocks — do NOT add or remove blocks
3. KEEP the same word distribution per block (if a block has 2 words, keep 2 words)
4. ONLY fix the text content below timestamps
5. Restore original characters from voice (e.g. "$108,000" not "one hundred eight thousand", "S&P 500" not "S and P five hundred")
6. Preserve natural capitalization (proper nouns, acronyms, brand names)
7. Return the complete corrected SRT (plain text only — NO json, NO markdown)

ORIGINAL VOICE:
{{VOICE}}

WHISPER SRT (check and fix if needed):
{{SRT}}`;

/**
 * Dùng AI để sửa text trong SRT cho đúng với voice gốc.
 * Timing (timestamp) được giữ nguyên — chỉ text bị sửa.
 *
 * @param {{ stt: number, voice: string, srtContent: string, language: string, keys: object, onLog?: Function }} opts
 * @returns {Promise<string>} SRT đã sửa
 */
export async function fixSRTWithAI({ stt, voice, srtContent, language = 'vi', keys, onLog }) {
  if (!srtContent?.trim()) return srtContent;
  if (!voice?.trim()) return srtContent;

  // Đếm số block để validate sau khi AI fix
  const blockCount = (srtContent.trim().split(/\n{2,}/).length);
  if (blockCount === 0) return srtContent;

  const promptTemplate = language === 'en' ? SRT_FIX_PROMPT_EN : SRT_FIX_PROMPT_VI;
  const prompt = promptTemplate
    .replace('{{VOICE}}', voice.trim())
    .replace('{{SRT}}', srtContent.trim());

  onLog?.(`AI SRT fix cảnh ${stt} (${language.toUpperCase()}, ${blockCount} blocks)...`);

  try {
    const { result } = await callAI({ prompt, isJson: false, keys, onLog });
    const fixed = String(result || '').trim();

    if (!fixed) {
      onLog?.(`AI SRT fix cảnh ${stt}: AI trả về rỗng — giữ SRT gốc`);
      return srtContent;
    }

    // Validate: số block phải khớp với bản gốc
    const fixedBlocks = fixed.trim().split(/\n{2,}/).length;
    if (fixedBlocks !== blockCount) {
      onLog?.(`AI SRT fix cảnh ${stt}: số block thay đổi (${blockCount} → ${fixedBlocks}) — giữ SRT gốc`);
      return srtContent;
    }

    // Validate: vẫn còn timestamp (không bị AI xóa)
    if (!fixed.includes('-->')) {
      onLog?.(`AI SRT fix cảnh ${stt}: AI xóa mất timestamp — giữ SRT gốc`);
      return srtContent;
    }

    onLog?.(`✓ AI SRT fix cảnh ${stt}: OK (${blockCount} blocks)`);
    return fixed + '\n';
  } catch (e) {
    onLog?.(`AI SRT fix cảnh ${stt}: lỗi — giữ SRT gốc (${e.message.slice(0, 80)})`);
    return srtContent;
  }
}

// EOF: agents/srtFixAgent.js
